test.message=Hello from Config Server - Course Service

server.port=8081
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/course_db}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-4-6

spring.cloud.openfeign.httpclient.hc5.enabled=true