test.message=Hello from Config Server - Enrollment Service

server.port=8082
spring.data.mongodb.uri=mongodb://localhost:27018/enrollment_db
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.listener.simple.default-requeue-rejected=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true