server.port=8080

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.cloud.gateway.server.webflux.routes[0].id=course-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://course-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/courses/**,/auth/**,/users/**,/ai/**

spring.cloud.gateway.server.webflux.routes[1].id=enrollment-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://enrollment-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/enrollments/**