spring.config.import=optional:file:.env[.properties],optional:file:course-service/.env[.properties],optional:configserver:http://localhost:8888

spring.application.name=course-service
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/course_db

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}