spring.application.name=course-service
server.port=8081

spring.mongodb.uri=mongodb://localhost:27017/course_db

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb24xMjM0NTY=
jwt.expiration=86400000